# Generated by Django 4.2 on 2023-05-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='county',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
    ]
